"use client";
import "./globals.css";
import { CityProvider } from "./hooks/useCity";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

/* export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="theme-color" content="#fff" />
      </head>
      <body className={inter.className}>
        <CityProvider>{children}</CityProvider>
      </body>
    </html>
  );
}
